export const THEMES = {
  light: {
    id: 'light',
    label: 'Light',
    background: '#f0f0e8',
    gridColor: '#bbb',
    gridGlow: null,
    gridLineWidth: 1,
    bikeColor: '#00fff2',
    bikeStroke: '#00cccc',
    trailGlow: false,
    blockStroke: '#334',
    hudBorder: null,
    hudText: '#aaa',
    hudAccent: '#0ff',
    scanlines: false,
    wireframe: false,
    gradient: null,
  },
  neon: {
    id: 'neon',
    label: 'Neon',
    background: '#0a0a14',
    gridColor: 'rgba(0, 255, 242, 0.15)',
    gridGlow: 'rgba(0, 255, 242, 0.3)',
    gridLineWidth: 0.8,
    bikeColor: '#00fff2',
    bikeStroke: '#00cccc',
    trailGlow: true,
    blockStroke: '#334',
    hudBorder: 'rgba(0, 255, 242, 0.4)',
    hudText: '#aaa',
    hudAccent: '#0ff',
    scanlines: false,
    wireframe: false,
    gradient: null,
  },
  synthwave: {
    id: 'synthwave',
    label: 'Synthwave',
    background: null, // uses gradient
    gridColor: 'rgba(255, 0, 200, 0.25)',
    gridGlow: 'rgba(255, 0, 200, 0.4)',
    gridLineWidth: 0.8,
    bikeColor: '#e0e0ff',
    bikeStroke: '#aaaadd',
    trailGlow: true,
    blockStroke: '#446',
    hudBorder: 'rgba(255, 0, 200, 0.4)',
    hudText: '#cca',
    hudAccent: '#ff80e0',
    scanlines: false,
    wireframe: false,
    gradient: {
      stops: [
        [0, '#1a0030'],
        [0.5, '#2a0050'],
        [1, '#0a0028'],
      ],
    },
  },
  retro: {
    id: 'retro',
    label: 'Retro',
    background: '#0a0a0a',
    gridColor: 'rgba(0, 255, 0, 0.15)',
    gridGlow: 'rgba(0, 255, 0, 0.2)',
    gridLineWidth: 0.6,
    bikeColor: '#00ff00',
    bikeStroke: '#00aa00',
    trailGlow: true,
    blockStroke: '#030',
    hudBorder: 'rgba(0, 255, 0, 0.3)',
    hudText: '#0a0',
    hudAccent: '#0f0',
    scanlines: true,
    wireframe: false,
    gradient: null,
  },
  blueprint: {
    id: 'blueprint',
    label: 'Blueprint',
    background: '#0a1628',
    gridColor: 'rgba(80, 140, 255, 0.2)',
    gridGlow: null,
    gridLineWidth: 0.5,
    bikeColor: '#4488ff',
    bikeStroke: '#2266cc',
    trailGlow: false,
    blockStroke: '#4488ff',
    hudBorder: 'rgba(80, 140, 255, 0.3)',
    hudText: '#4488ff',
    hudAccent: '#88bbff',
    scanlines: false,
    wireframe: true,
    gradient: null,
  },
};

export const THEME_LIST = Object.values(THEMES);
export const THEME_IDS = Object.keys(THEMES);

export function getNextTheme(currentId) {
  const idx = THEME_IDS.indexOf(currentId);
  const nextIdx = (idx + 1) % THEME_IDS.length;
  return THEMES[THEME_IDS[nextIdx]];
}
